unqualified-search-registries = ["docker.io"]

[[registry]]
location = "docker.io"

[[registry.mirror]]
location = "docker.1ms.run"

[[registry.mirror]]
location = "docker.mybacc.com"

[[registry.mirror]]
location = "dytt.online"

[[registry.mirror]]
location = "lispy.org"

[[registry.mirror]]
location = "docker.xiaogenban1993.com"

[[registry.mirror]]
location = "docker.yomansunter.com"

[[registry.mirror]]
location = "aicarbon.xyz"

[[registry.mirror]]
location = "666860.xyz"

[[registry.mirror]]
location = "docker.zhai.cm"

[[registry.mirror]]
location = "a.ussh.net"

[[registry.mirror]]
location = "hub.littlediary.cn"

[[registry.mirror]]
location = "hub.rat.dev"

[[registry.mirror]]
location = "docker.m.daocloud.io"

[[registry.mirror]]
location = "dockerproxy.net"